version: 3.1.{build}
branches:
  only:
    - dev
environment:
  matrix:
    - COMPILER: mingw
      MINGW_DIR: c:\msys64\mingw32

before_build:
  - set Path=%MINGW_DIR%\bin;%Path%

build_script:
  - set Path=%MINGW_DIR%\bin;c:\msys64\usr\bin;
  - bash autogen.sh
  - cd src/lib
  - make
